---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: bookinfo-routes
  namespace: bookinfo
  labels:
    domain: 'demo.mtritaba.com'
spec:
  routes:
  - matchers:
     # the path matchers in this RouteTable can begin with any prefix
    - prefix: /productpage
    - prefix: /static
    - prefix: /login
    - prefix: /logout
    - prefix: /api/v1/products
    - prefix: /callback
    routeAction:
      single:
        upstream:
          name: bookinfo-productpage-9080
          namespace: gloo-system
